In [256]:
import numpy as np
import pandas as pd
from tslearn.utils import to_time_series, to_time_series_dataset
from tslearn.neighbors import KNeighborsTimeSeries

In [269]:
nN = 3
init = 100
test_points = 10
out_dim = 2

data = [np.random.rand(10,21) for _ in range(init)]
labels = np.array([list((np.random.randn(1,out_dim)+2)[0]) for _ in range(init)])

Transforming data to tslearn format

In [270]:
time_series = to_time_series_dataset(data)
time_series.shape

(100, 10, 21)

Unknown points

In [271]:
# test = data[0] # same as first known point

test = [np.random.rand(10,21) for _ in range(test_points)]
labels_test = np.array([list((np.random.randn(1,out_dim)+4)[0]) for _ in range(test_points)])

test_time_series = to_time_series_dataset(test)

print(test_time_series.shape)
# print(pred)

(10, 10, 21)


In [272]:
knn = KNeighborsTimeSeries(n_neighbors=nN).fit(time_series)

In [273]:
def knnUncertainty(nN,pred, test_time_series,labels,knn):

    pred = labels
    sigma = []
    distances, indices = knn.kneighbors(test_time_series,nN, return_distance=True)
    
    for i in range(len(test_time_series)):
        # print(i)
        dist = distances[i]
        print(dist)
        ind = (indices[i])
        print(ind)
        #calculate the nearest point error
        pred_near = pred[i]
        # print(pred_near)
        # print(ind)

        abs_err = np.abs(pred_near - labels[ind])
        print(abs_err)
        weights = 1 - (dist / dist.sum())
        print(weights)
        print(weights.shape)
        weights = np.broadcast_to(weights.reshape(len(ind), 1), (len(ind), out_dim))
        print(weights)
        weighted_err = np.mean(np.average(abs_err, weights=weights**nN) )

        nbrs_y = list(labels[ind])
        nbrs_y.append(pred[i])
        nbrs_var = np.std(nbrs_y)

        min_dist = np.min(dist)
        pred_var = weighted_err + min_dist * nbrs_var
        sigma.append(pred_var)
    sigma = np.array(sigma)
    return sigma

In [274]:
knnUncertainty(nN, labels_test, test_time_series,labels,knn)

[5.2643433  5.41558662 5.54684449]
[46 34 42]
[[0.64592201 1.05109316]
 [1.43836852 0.81812986]
 [0.86905284 0.14826472]]
[0.67557672 0.66625612 0.65816715]
(3,)
[[0.67557672 0.67557672]
 [0.66625612 0.66625612]
 [0.65816715 0.65816715]]
[5.44560712 5.56663624 5.59348647]
[58 11 29]
[[3.07817542 1.93968735]
 [0.63568681 1.59110127]
 [0.04326981 2.54575376]]
[0.67206457 0.66477618 0.66315925]
(3,)
[[0.67206457 0.67206457]
 [0.66477618 0.66477618]
 [0.66315925 0.66315925]]
[5.02317208 5.33090485 5.35243949]
[48 34 49]
[[3.11419217 0.72120271]
 [1.30429846 0.51836893]
 [0.48447942 0.64837089]]
[0.68018548 0.66059279 0.65922173]
(3,)
[[0.68018548 0.68018548]
 [0.66059279 0.66059279]
 [0.65922173 0.65922173]]
[5.48248623 5.61529483 5.6346348 ]
[45 48 51]
[[0.64189294 0.35909883]
 [2.72662592 1.06899011]
 [0.83701687 0.65930276]]
[0.67234342 0.66440621 0.66325037]
(3,)
[[0.67234342 0.67234342]
 [0.66440621 0.66440621]
 [0.66325037 0.66325037]]
[5.23867517 5.35932812 5.36932838]
[65 70 86]
[[

array([3.84825754, 7.70857041, 5.77587514, 6.38531108, 3.09688956,
       6.09853551, 5.07023043, 7.57313867, 4.59558623, 5.58583906])

In [ ]:
array([4.1884983 , 1.53541475, 1.5085826 , 2.83379748, 2.94832207,
       1.98689609, 1.92418307, 2.25995833, 2.40071495, 2.42274423])

In [234]:
a = np.array([[0,         0],
 [0.05709389, 0.24707099],
 [0.48952425, 0.23022069]])

In [134]:
a

array([[0.        , 0.        ],
       [0.05709389, 0.24707099],
       [0.48952425, 0.23022069]])

In [137]:
weights = np.array([1, 0.51519018, 0.48480982])
weights

array([1.        , 0.51519018, 0.48480982])

In [215]:
weights.transpose().shape

(3,)

In [213]:
weights.shape

(3,)

In [208]:
weights2 = np.concatenate([[weights, weights]]).transpose()
weights2

array([[1.        , 1.        ],
       [0.51519018, 0.51519018],
       [0.48480982, 0.48480982]])

In [210]:
weights

array([1.        , 0.51519018, 0.48480982])

In [221]:
weights.reshape(3,1)

array([[1.        ],
       [0.51519018],
       [0.48480982]])

In [237]:
weights2 = np.broadcast_to(weights.reshape(3,1), (3,2))

In [136]:
np.mean(np.average(a, axis=0, weights=weights))

0.1264105435210473

In [238]:
np.average(a, weights=weights2)

0.12641054352104727